<style>
  .mods-table {
    width: 100%;
  }
  .page-header {
  margin-top: 100px;
  display: flex;
  align-items: flex-end;
  position: relative;
  padding-bottom: 10px;
  justify-content: space-between
}

/* Zajištění pozadí pro překrytí čáry pod textem */
.page-header h1,
.page-nav {
  position: relative;
  z-index: 1;
}

.page-header h1 {
  margin: 0;
  font-size: 24px;
  color: #e0e0e0;
}

.page-nav {
  display: flex;
  gap: 20px;
}

.page-nav a {
  text-decoration: none;
  color: #ccc;
  font-weight: 500;
  position: relative;
  padding-bottom: 6px;
  margin-left: 20px;
}
.page-nav a::after {
  content: '';
  position: absolute;
  left: 0;
  bottom: 0;
  width: 100%;
  height: 3px;
  background-color: transparent;
  transition: background-color 0.3s;
}
.page-nav a:hover::after {
  background-color: #555;
}
.page-nav a.active-link::after {
  content: '';
  position: absolute;
  bottom: -3px;
  width: 100%;
  height: 3px;
  background-color: #82cfff;
}

</style>